edge_line:
  width: 0.5
  color: "#888"
node_marker:
  showscale: true
  colorscale: "YlGnBu"
  color: []
  size: 10
layout:
  showlegend: false
  hovermode: "closest"
  margin:
    b: 0
    l: 0
    r: 0
    t: 0
